### ISSUE TITLE
axoloti 2.0

### ISSUE THREAD

**Issue by koraysels** [maceq687/axoloti#1]
Hi, I was trying to get your pages patch and the complex poly patch to run on my axoctrl but i recentrly updated my axoloti core to 2.0 and it does not seem to work with your patches.. Have you managed to get them to run on 2.0?

```
compiling /Users/koraysels/Documents/axoloti-2.0.0/build/xpatch.cpp
/Users/koraysels/Documents/axoloti-2.0.0/build/xpatch.cpp: In member function 'int rootc::instanceconfig__1::init(rootc*)':
/Users/koraysels/Documents/axoloti-2.0.0/build/xpatch.cpp:1764:24: error: variable 'const I2CConfig i2cfg' has initializer but incomplete type
 static const I2CConfig i2cfg = {
                        ^~~~~
/Users/koraysels/Documents/axoloti-2.0.0/build/xpatch.cpp:1765:5: error: 'OPMODE_I2C' was not declared in this scope
     OPMODE_I2C,
     ^~~~~~~~~~
/Users/koraysels/Documents/axoloti-2.0.0/build/xpatch.cpp:1765:5: note: suggested alternative: 'TIME_I2S'
     OPMODE_I2C,
     ^~~~~~~~~~
     TIME_I2S
/Users/koraysels/Documents/axoloti-2.0.0/build/xpatch.cpp:1767:5: error: 'FAST_DUTY_CYCLE_2' was not declared in this scope
     FAST_DUTY_CYCLE_2,
     ^~~~~~~~~~~~~~~~~
/Users/koraysels/Documents/axoloti-2.0.0/build/xpatch.cpp: In member function 'int rootc::instanceOLED128x64nice__1::init(rootc*)':
/Users/koraysels/Documents/axoloti-2.0.0/build/xpatch.cpp:2290:88: warning: invalid conversion from 'msg_t (*)(void*) {aka long int (*)(void*)}' to 'tfunc_t {aka void (*)(void*)}' [-fpermissive]
 Thd = chThdCreateStatic(waThreadX, sizeof(waThreadX), NORMALPRIO, ThreadX, (void *)this);
                                                                                        ^
In file included from /Applications/Axoloti.app/Contents/Java/api/xpatch.h:27:0,
                 from <command-line>:0:
/Applications/Axoloti.app/Contents/Java/api/ch.h:954:13: note:   initializing argument 4 of 'thread_t* chThdCreateStatic(void*, size_t, tprio_t, tfunc_t, void*)'
   thread_t *chThdCreateStatic(void *wsp, size_t size,
             ^~~~~~~~~~~~~~~~~
make: *** [/Users/koraysels/Documents/axoloti-2.0.0/build/xpatch.o] Error 1
Compiling patch failed

```

**Comment by koraysels** [comment]
dpwngrading to v1 worked though.. using that for now! thanks so much!

**Comment by maceq687** [comment]
I've used the latest version (1.0.12) for the Pages patch. Version 2.0 is in pre-release state and it is known some some of the community-made objects (that I'm utilising in my patches) won't work in 2.0 straight away.
